const AdminLog = require('../models/AdminLog');
const { generateCSV, generateExcel, generatePDF } = require('../utils/exportUtils');

// @desc    Get admin logs with filtering and pagination
// @route   GET /api/logs
// @access  Private/Admin
const getLogs = async (req, res) => {
  try {
    const { 
      page = 1, 
      limit = 20, 
      startDate, 
      endDate, 
      adminId, 
      action, 
      entity 
    } = req.query;

    const query = {};

    // Date filtering
    if (startDate || endDate) {
      query.timestamp = {};
      if (startDate) query.timestamp.$gte = new Date(startDate);
      if (endDate) query.timestamp.$lte = new Date(endDate);
    }

    // Other filters
    if (adminId) query.adminId = adminId;
    if (action) query.action = action;
    if (entity) query.entity = entity;

    const logs = await AdminLog.find(query)
      .sort({ timestamp: -1 })
      .limit(limit * 1)
      .skip((page - 1) * limit)
      .exec();

    const count = await AdminLog.countDocuments(query);

    res.json({
      logs,
      totalPages: Math.ceil(count / limit),
      currentPage: page,
      totalLogs: count
    });
  } catch (error) {
    res.status(500).json({ message: error.message });
  }
};

// @desc    Export admin logs
// @route   GET /api/logs/export
// @access  Private/Admin
const exportLogs = async (req, res) => {
  try {
    const { 
      startDate, 
      endDate, 
      adminId, 
      action, 
      entity,
      format = 'csv'
    } = req.query;

    const query = {};

    if (startDate || endDate) {
      query.timestamp = {};
      if (startDate) query.timestamp.$gte = new Date(startDate);
      if (endDate) query.timestamp.$lte = new Date(endDate);
    }

    if (adminId) query.adminId = adminId;
    if (action) query.action = action;
    if (entity) query.entity = entity;

    const logs = await AdminLog.find(query).sort({ timestamp: -1 });

    const data = logs.map(log => ({
      Date: new Date(log.timestamp).toLocaleString(),
      Admin: log.adminName,
      Action: log.action,
      Entity: log.entity,
      Details: JSON.stringify(log.details || {}),
      IP: log.ipAddress
    }));

    const columns = [
      { key: 'Date', header: 'Date', width: 20 },
      { key: 'Admin', header: 'Admin', width: 15 },
      { key: 'Action', header: 'Action', width: 15 },
      { key: 'Entity', header: 'Entity', width: 15 },
      { key: 'Details', header: 'Details', width: 30 },
      { key: 'IP', header: 'IP Address', width: 15 }
    ];

    const config = {
      title: 'Admin Activity Log',
      columns,
      metadata: {
        'Generated By': req.user.name,
        'Date Range': `${startDate || 'All'} to ${endDate || 'All'}`
      }
    };

    let buffer;
    let contentType;
    let filename;

    switch (format.toLowerCase()) {
      case 'pdf':
        buffer = await generatePDF(data, config);
        contentType = 'application/pdf';
        filename = 'admin_logs.pdf';
        break;
      case 'excel':
        buffer = await generateExcel(data, config);
        contentType = 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet';
        filename = 'admin_logs.xlsx';
        break;
      case 'csv':
      default:
        buffer = await generateCSV(data, config);
        contentType = 'text/csv';
        filename = 'admin_logs.csv';
        break;
    }

    res.setHeader('Content-Type', contentType);
    res.setHeader('Content-Disposition', `attachment; filename=${filename}`);
    res.send(buffer);

  } catch (error) {
    console.error('Export error:', error);
    res.status(500).json({ message: 'Error generating export' });
  }
};

module.exports = {
  getLogs,
  exportLogs
};
